services:
  redis:
    image: redis:7
    container_name: redis
    command: [
        "redis-server",
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
